# User config
author: ""
tagline: "Stellas portfolio"
description: "I like to decorate my town in Animal Crossing and go on hikes with friends. Oh and I also enjoy building pretty stuff that eventually works."
keywords: "Stella, coding, front-end, design, mock-up, project"
email: "biliou.stella@gmail.com"
linkedin: "https://www.linkedin.com/in/stella-biliou"
twitter: "https://twitter.com/"
github: "https://github.com/stellitzab"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
