# User config
author: ""
tagline: "Stellas portfolio"
description: "I spend a lot of time at my desk. Either learning new stuff, doing school work, editing photos from my latest trip or playing games."
keywords: "Stella, coding, front-end, design, mock-up, project"
email: "biliou.stella@gmail.com"
linkedin: "https://www.linkedin.com/in/stella-biliou"
github: "https://github.com/stellitzab"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
